#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/apptest?useSSL=false&createDatabaseIfNotExists=true
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_DATABASE}?useSSL=false
    username: postgres
    password: 2jdz5ZYtpx5OxzjV
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true